### ISSUE TITLE
获取文章url别限制之后，要多久能恢复呢

### ISSUE THREAD

**Issue by papillonyi** [wnma3mz/wechat_articles_spider#19]
获取文章url接口用多了之后，就一直不能用了，要多久能恢复啊

**Comment by wnma3mz** [comment]
> 获取文章url接口用多了之后，就一直不能用了，要多久能恢复啊

一天

**Comment by jun-jing** [comment]
我也出现类似情况了, 提示
`
Traceback (most recent call last):
  File "e:/CodeProject/wechat_articles_spider/test/test_WechatUrls.py", line 14, in <module>
    article_data = paw.get_urls(nickname, begin="0", count="5")
  File "D:\software\Python\Python37\lib\site-packages\wechatarticles\ArticlesUrls.py", line 342, in get_urls
    raise Exception(u"公众号名称错误或cookie、token错误，请重新输入")
Exception: 公众号名称错误或cookie、token错误，请重新输入
`
检查了几遍token和cookie, 昨晚还可以用, 等一天看看吧.
